<?php

namespace App\Repository;

/**
 * FormEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
